spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver        # mysql驱动
    url: jdbc:mysql://localhost:3306/bms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai      # 数据库连接配置
    username: root      # 数据库用户名
    password: 123456        # 数据库密码
    druid:
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 20  # 最大
      max-wait: 60000  # 连接超时时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: select 0
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时，是否测试该连接
      filters: config,wall,stat
  application:
    name: bms        # 服务名称

server:
  port: 6001      # 端口
  servlet:
    context-path: /bms

### 转发配置
proxy:
  target-addr: http://172.253.64.103:9090     # 代理转发路径
  target-prefix: proxy    # 代理前缀标示
  ttl: 720    # token超时时间，分钟


### log4j2配置
logging:
  config: classpath:log4j2.xml

mybatis:
  mapper-locations: classpath:mybites.mapper/*.xml
  type-aliases-package: com.hekf.web
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
